require("plugin.lazy")
require("plugin.config.colorscheme")
require("plugin.config.nvim_tree")
require("plugin.config.lsp_config")
require("plugin.config.snippets")
require("plugin.config.treesitter")
require'colorizer'.setup()
